server:
  port: 8885

spring:
  application:
    name: caja-service
  cloud:
    config:
      enabled: false

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: true

denominaciones: 2000,5000,10000,20000,50000,100000
cantiadad_denominaciones: 5,5,5,5,5,5

