server:
  port: 8080

spring:
  application:
    name: image-service
  cloud:
    config:
      enabled: false

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: true

message: Hola, esta es la configuración por defecto.